name: breathing test

on: push

jobs:
  basic_test:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: 'breathing test'
      run: |
        echo '::error ::Something went wrong'
        echo $(ls -lart)
        export SINGLE_ERROR="$(cat test/Inputs/single_error.txt)"
        echo "::error ::$SINGLE_ERROR"


