name: breathing test

on: push

jobs:
  basic_test:
    runs-on: [ubuntu-latest]
    steps:
    - name: "checkout"
      uses: actions/checkout@v2
    - name: 'breathing test'
      run: |
        echo '::error ::Something went wrong'
        echo $(ls -lart)
        export SINGLE_ERROR="$(cat test/Inputs/single_error.txt)"
        echo "::error ::$SINGLE_ERROR"
    - name: 'action test'
      uses: ./javascript-action/
    - name: 'test problem matcher'
      run: |
        echo "::add-matcher::lit-problem-matcher.json"
        cat test/Inputs/libcxx_logs.txt
        echo "::remove-matcher owner=lit-problem-matcher::"


